import * as React from 'react'
import { TNextLayout } from 'next'
import Head from 'next/head'
import Header from 'components/Layout/Header'
import Footer from 'components/Layout/Footer'

type TBasicLayout = {
  children: React.ReactNode
}

const Layout: TNextLayout<TBasicLayout> = ({ children }): JSX.Element => {
  return (
    <div className='flex flex-col justify-center min-h-screen bg-[#e7e8f434] w-screen text-base-content'>
      <Head>
        <title>{process.env.NEXT_PUBLIC_SITE_TITLE}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon-package/favicon.ico' />
      </Head>

      <Header />
      <main className='mt-20 flex flex-grow justify-center w-full min-h-full text-center font-normal tracking-normal xl:bg-[url(/background.png)] bg-no-repeat xl:bg-cover'>
        <div className='flex flex-col max-w-3xl sm:w-full max-h-screen pb-12 bg-gray-50 rounded-md'>
          {children}
        </div>
      </main>
      <Footer />
    </div>
  )
}
export default Layout
