import * as React from 'react'
import { TNextLayout } from 'next'
import Head from 'next/head'
import Header from 'components/Layout/Header'
import Banner from 'components/Layout/Banner'
import Footer from 'components/Layout/Footer'
import Countdown from 'components/Countdown'

type TBasicLayout = {
  children: React.ReactNode
}

const Layout: TNextLayout<TBasicLayout> = ({ children }): JSX.Element => {
  return (
    <div className='flex flex-col items-center justify-center min-h-screen bg-[#e7e8f434] w-screen text-base-content'>
      <Head>
        <title>{process.env.NEXT_PUBLIC_SITE_TITLE}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon-package/favicon.ico' />
      </Head>

      <Header />
      <main className='flex flex-1 p-2 justify-center w-full text-center font-normal tracking-normal bg-[url(/background.png)] bg-no-repeat bg-cover'>
        <div className='relative max-w-3xl sm:w-full max-h-screen mt-12'>
          <Banner />
          <Countdown />
          {children}
          <div className='absolute inset-y-1/2 bg-[url(/hero.png)] w-full h-3/5 bg-no-repeat bg-contain'></div>
        </div>
      </main>
      <Footer />
    </div>
  )
}
export default Layout
